# The status generator command.
# Optional: with no status generator the bar will display only tags and layout name.
# command = "your command here"

# The font and various sizes
font = "monospace 10"
height = 24
margin_top = 0
margin_bottom = 0
margin_left = 0
margin_right = 0
separator_width = 2.0
tags_r = 0.0
tags_padding = 25.0
tags_margin = 0.0
blocks_r = 0.0
blocks_overlap = 0.0

# Misc
position = "top" # either "top" or "bottom"
layer = "top" # one of "top", "overlay", "bottom" or "background"

invert_touchpad_scrolling = true
start_hidden = false # whether the bar is initially in the 'hidden' state

[theme.focused]
# Colors
background = "#282828ff"
color = "#ffffffff"
separator = "#9a8a62ff"
tag_fg = "#d79921ff"
tag_bg = "#282828ff"
tag_focused_fg = "#1d2021ff"
tag_focused_bg = "#689d68ff"
tag_urgent_fg = "#282828ff"
tag_urgent_bg = "#cc241dff"
tag_inactive_fg = "#d79921ff"
tag_inactive_bg = "#282828ff"
blend = true # whether tags/blocks colors should blend with bar's background

# Tab bar settings
hide_inactive_tags = true
show_tags = true
show_layout_name = true
show_mode = true

[theme.unfocused]
# Empty by default, as it inherits all unset values from the `focused` theme.
# You can, for example, use a darker white, to show that its unfocused:
# color = "0xbbbbbbff"
# tag_fg = "0xbbbbbbff"
# tag_focused_fg = "0xbbbbbbff"
# tag_inactive_fg = "0xbbbbbbff"
# tag_urgent_fg = "0xbbbbbbff"

# WM-specific options
[wm.river]
max_tag = 9 # Show only the first nine tags

# Per output overrides
# [output.your-output-name]
# right now only "enable" option is available
# enable = false
#
# You can have any number of overrides
# [output.eDP-1]
# enable = false
